notifications:
  email: false
language: go
go:
  - "1.8"
install:
  - "wget https://github.com/coreos/etcd/releases/download/v3.1.2/etcd-v3.1.2-linux-amd64.tar.gz"
  - "tar -zxvf etcd-v3.1.2-linux-amd64.tar.gz"
  - "etcd-v3.1.2-linux-amd64/etcd -name travis &"
  - "sleep 5" # Wait for etcd to come up
cache: apt
script: "curl http://127.0.0.1:4001 && make get && make test"
