notifications:
  email: false
language: go
go:
  - "1.2"
install:
  - "wget https://github.com/coreos/etcd/releases/download/v0.4.4/etcd-v0.4.4-linux-amd64.tar.gz"
  - "tar -zxvf etcd-v0.4.4-linux-amd64.tar.gz"
  - "etcd-v0.4.4-linux-amd64/etcd -name travis &"
  - "sleep 5" # Wait for etcd to come up
cache: apt
script: "curl http://127.0.0.1:4001 && make get && make test"
