notifications:
  email: false
language: go
go:
  - "1.2"
install:
  - "wget https://github.com/coreos/etcd/releases/download/v2.0.3/etcd-v2.0.3-linux-amd64.tar.gz"
  - "tar -zxvf etcd-v2.0.3-linux-amd64.tar.gz"
  - "etcd-v2.0.3-linux-amd64/etcd -name travis &"
  - "sleep 5" # Wait for etcd to come up
cache: apt
script: "make get && make test"
